# Generated by Django 4.0.4 on 2022-05-25 01:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("is_Active", models.BooleanField()),
            ],
        ),
    ]
