# Generated by Django 4.0.4 on 2022-05-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentinfo", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinfo",
            name="is_Active",
            field=models.BooleanField(null=True),
        ),
    ]
