# Generated by Django 4.0.4 on 2022-05-25 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', to='fee.fee')),
            ],
        ),
    ]
